server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_parttime?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: abc123456789012345678901234567890
  expire: 7